# Generated by Django 5.1.15 on 2025-12-11 13:48

import django.contrib.postgres.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('user_role', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('profile_image', models.CharField(max_length=400, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('referral_code', models.CharField(max_length=20, null=True)),
                ('mobile', models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('device_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_master',
                'indexes': [models.Index(fields=['mobile'], name='user_master_mobile_5e91e5_idx'), models.Index(fields=['email'], name='user_master_email_19d8d3_idx'), models.Index(fields=['username'], name='user_master_usernam_008aa9_idx')],
            },
        ),
    ]
