# Generated by Django 5.1.15 on 2026-01-28 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'reviewmedia',
            },
        ),
        migrations.AddIndex(
            model_name='productreviews',
            index=models.Index(fields=['product_id'], name='productrevi_product_818b75_idx'),
        ),
        migrations.AlterModelTable(
            name='ordersequence',
            table='order_sequence',
        ),
        migrations.AlterModelTable(
            name='storesequence',
            table='store_sequence',
        ),
        migrations.AddField(
            model_name='productreviewmedia',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='db.productreviews'),
        ),
    ]
