# Generated by Django 5.1.15 on 2026-01-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
