# Generated by Django 5.1.15 on 2026-01-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='lsin',
            field=models.CharField(db_index=True, help_text='Lifeboat standard identification number. Business-facing display product ID', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('store', 'lsin')},
        ),
        migrations.CreateModel(
            name='StoreSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('last_lsin_number', models.PositiveIntegerField(default=0)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
