# Generated by Django 5.1.15 on 2026-01-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webbanner',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='webbanner',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
