# Generated by Django 5.1.15 on 2025-12-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMaster',
            new_name='User',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_mobile_1f5d42_idx',
            old_name='user_master_mobile_5e91e5_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_email_7bbb4c_idx',
            old_name='user_master_email_19d8d3_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_usernam_b79065_idx',
            old_name='user_master_usernam_008aa9_idx',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
