# Generated by Django 5.1.15 on 2026-01-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='refresh_token',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_token',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
