# Generated by Django 5.1.15 on 2025-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cashfree_order_orderproducts_ordershippingdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmaster',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
