# Generated by Django 5.1.15 on 2026-01-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_webbanner_description_webbanner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
