# Generated by Django 5.1.15 on 2026-01-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_pincode_state'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pincode',
            index=models.Index(fields=['pin'], name='pincode_pin_6740e6_idx'),
        ),
    ]
