# Generated by Django 5.1.15 on 2026-02-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_pincode_pincode_pin_6740e6_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pincode',
            old_name='area',
            new_name='district',
        ),
        migrations.AlterField(
            model_name='pincode',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
