# Generated by Django 5.1.15 on 2026-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_addressmaster_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inr',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp_others',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price_others',
            field=models.JSONField(null=True),
        ),
    ]
