# Generated by Django 5.1.15 on 2025-12-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
