# Generated by Django 5.1.15 on 2026-01-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_product_inr_alter_product_mrp_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
    ]
