# Generated by Django 5.1.15 on 2026-02-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_area_pincode_district_alter_pincode_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
    ]
