# Generated by Django 5.1.15 on 2025-12-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rename_first_name_user_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
