# Generated by Django 5.1.15 on 2026-02-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('os', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('min_supported_version', models.CharField(max_length=20)),
                ('latest_version', models.CharField(max_length=20)),
                ('force_update', models.BooleanField(default=False)),
                ('update_title', models.CharField(blank=True, max_length=100, null=True)),
                ('update_message', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'version_configuration',
                'indexes': [models.Index(fields=['os', 'latest_version', 'is_active'], name='version_con_os_cab345_idx')],
            },
        ),
    ]
