# Generated by Django 5.1.15 on 2026-01-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_pincode_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='screen',
            field=models.CharField(choices=[('Home', 'Home'), ('Wishlist', 'Wishlist')], max_length=20),
        ),
    ]
