# Generated by Django 5.1.15 on 2026-02-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_appversionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_slip',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
