# Generated by Django 5.1.15 on 2026-01-02 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_banner_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('quantity', models.PositiveIntegerField()),
                ('user_id', models.UUIDField()),
            ],
            options={
                'db_table': 'cart',
                'indexes': [models.Index(fields=['user_id'], name='cart_user_id_9b8b23_idx'), models.Index(fields=['product_id'], name='cart_product_8a6792_idx')],
                'unique_together': {('user_id', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
            ],
            options={
                'db_table': 'wishlist',
                'indexes': [models.Index(fields=['user_id'], name='wishlist_user_id_2af636_idx'), models.Index(fields=['product_id'], name='wishlist_product_ab5d67_idx')],
                'unique_together': {('user_id', 'product_id')},
            },
        ),
    ]
