# Generated by Django 5.1.15 on 2025-12-17 10:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(null=True)),
                ('mobile', models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('email', models.EmailField(max_length=100, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_otp',
                'indexes': [models.Index(fields=['mobile', 'expires_at', 'otp'], name='user_otp_mobile_db38f5_idx'), models.Index(fields=['email', 'expires_at', 'otp'], name='user_otp_email_ea5967_idx')],
            },
        ),
    ]
