# Generated by Django 5.1.15 on 2026-02-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_order_shipping_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sms_auth_key',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sms_delivered_template_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sms_order_template_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sms_otp_template_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sms_packed_template_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sms_sender_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sms_shipped_template_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
