# Generated by Django 5.1.15 on 2025-12-17 12:14

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_userotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50, null=True)),
                ('colour', models.CharField(max_length=50, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.JSONField()),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), null=True, size=None)),
                ('videos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), null=True, size=None)),
                ('thumbnail_image', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
