# Generated by Django 5.1.15 on 2026-01-05 09:30

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_cart_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile', models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('email', models.EmailField(max_length=100, null=True)),
                ('device_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'temp_user',
                'indexes': [models.Index(fields=['mobile'], name='temp_user_mobile_ae2448_idx'), models.Index(fields=['email'], name='temp_user_email_2c7ac2_idx')],
            },
        ),
    ]
