# Generated by Django 5.1.15 on 2025-12-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='gst_percentage',
        ),
    ]
