# Generated by Django 5.1.15 on 2026-02-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_store_sms_auth_key_store_sms_delivered_template_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='breadth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Breadth in CM', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in CM', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in CM', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in KG', max_digits=8, null=True),
        ),
    ]
