# Generated by Django 5.1.15 on 2026-01-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_tempuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='pin',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
