# Generated by Django 5.1.15 on 2025-12-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_products_gst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gst_percentage',
            field=models.JSONField(null=True),
        ),
    ]
