# Generated by Django 5.1.15 on 2026-01-06 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_alter_pincode_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bonus_code', models.CharField(max_length=50)),
                ('short_title', models.CharField(max_length=50, null=True)),
                ('long_title', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('minimum_cart_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_percentage', models.CharField(max_length=50, null=True)),
                ('maximum_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms', models.CharField(max_length=1000, null=True)),
                ('validity_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
    ]
