# Generated by Django 5.1.15 on 2026-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_order_breadth_order_height_order_length_order_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('CREATED', 'Placed'), ('FAILED', 'Failed'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('REFUNDED', 'Refunded'), ('UNFULFILLED', 'Unfulfilled'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=30),
        ),
    ]
