# Generated by Django 5.1.15 on 2025-12-18 05:55

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_products_gst_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=255, null=True)),
                ('search_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDisplay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_product_id', models.UUIDField()),
                ('variant_product_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.UUIDField()),
                ('gender', models.CharField(max_length=20, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('search_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_tagline', models.CharField(max_length=100, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('highlights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('rating', models.CharField(max_length=20, null=True)),
                ('number_of_reviews', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'product display',
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='gst_percentage',
        ),
        migrations.RemoveField(
            model_name='products',
            name='selling_price',
        ),
    ]
