# Generated by Django 5.1.15 on 2026-01-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_coupon'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='displayproduct',
            table='display_product',
        ),
    ]
