# Generated by Django 5.1.15 on 2026-02-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeclient',
            name='identifier',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='storeclient',
            constraint=models.UniqueConstraint(fields=('store', 'identifier'), name='unique_identifier_per_store'),
        ),
    ]
