# Generated by Django 5.1.15 on 2025-12-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_category_productdisplay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gst_percentage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='mrp_others',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='selling_price_others',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
