# Generated by Django 5.1.15 on 2026-01-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_displayproduct_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='client_id',
            field=models.CharField(default='TEST1048858786a7530cc72f33d2ebe578588401', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='client_secret',
            field=models.CharField(default='cfsk_ma_test_518795086d308808f96e63f5d5db8c71_784dd231', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='url',
            field=models.CharField(default='https://sandbox.cashfree.com/pg/orders', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='webhook',
            field=models.CharField(default='https://dev-api.sru.ai/payment/paymentWebhook', max_length=100),
            preserve_default=False,
        ),
    ]
