# Generated by Django 5.1.15 on 2026-01-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_store_client_id_store_client_secret_store_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.store'),
        ),
    ]
