# Generated by Django 5.1.15 on 2026-02-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_alter_storeclient_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
