# Generated by Django 5.1.15 on 2025-12-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_products_gst_percentage_products_inr_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDisplay',
            new_name='DisplayProducts',
        ),
        migrations.AlterModelTable(
            name='displayproducts',
            table=' display products',
        ),
    ]
