# Generated by Django 5.1.15 on 2025-12-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_rename_productdisplay_displayproducts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displayproducts',
            name='category',
        ),
    ]
