# Generated by Django 5.1.15 on 2026-02-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_store_smtp_host_store_smtp_password_store_smtp_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='mobile_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_color',
            field=models.CharField(default='FFFFFF', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='secondary_color',
            field=models.CharField(default='FFFFFF', max_length=100),
        ),
    ]
