# Generated by Django 5.1.15 on 2026-02-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_store_email_login_store_mobile_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='aws_bucket_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='bo_subtitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='bo_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
