# Generated by Django 5.1.15 on 2025-12-18 06:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_remove_displayproducts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayproducts',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
    ]
