# Generated by Django 5.1.15 on 2025-12-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_displayproducts_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displayproducts',
            name='description',
        ),
    ]
