# Generated by Django 5.1.15 on 2026-02-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_store_aws_bucket_name_store_bo_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='NotificationChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('channel', models.CharField(choices=[('SMS', 'Sms'), ('WHATSAPP', 'Whatsapp'), ('EMAIL', 'Email'), ('PUSH', 'Push')], max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_user', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('fcm_server_key', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channel_configs', to='db.store')),
            ],
            options={
                'db_table': 'notification_channel_config',
                'unique_together': {('store', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('event', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_PACKED', 'Order Packed'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('OTP_AUTHENTICATION', 'Otp Authentication')], max_length=50)),
                ('channel', models.CharField(choices=[('SMS', 'Sms'), ('WHATSAPP', 'Whatsapp'), ('EMAIL', 'Email'), ('PUSH', 'Push')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='db.store')),
            ],
            options={
                'db_table': 'notification_template',
                'unique_together': {('store', 'event', 'channel')},
            },
        ),
    ]
