# Generated by Django 5.1.15 on 2026-01-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_user_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmaster',
            name='store',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='store',
        ),
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.RemoveField(
            model_name='displayproduct',
            name='store',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='store',
        ),
        migrations.RemoveField(
            model_name='ordershippingdetails',
            name='store',
        ),
        migrations.RemoveField(
            model_name='ordertimelines',
            name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
    ]
