# Generated by Django 5.1.15 on 2026-02-21 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_store_email_notificationchannelconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShippingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('name', models.CharField(max_length=100)),
                ('shipping_type', models.CharField(choices=[('FLAT', 'Flat Rate'), ('FREE_ABOVE', 'Free Above Amount'), ('STATE', 'State Based'), ('PINCODE', 'Pincode Based')], max_length=20)),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free_above_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_plans', to='db.store')),
            ],
            options={
                'db_table': 'shipping_plan',
            },
        ),
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='db.shippingplan')),
            ],
            options={
                'db_table': 'shipping_rule',
            },
        ),
    ]
