# Generated by Django 5.1.15 on 2025-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_remove_displayproducts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayproducts',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
