# Generated by Django 5.1.15 on 2026-02-21 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_store_email_notificationchannelconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='db.store'),
        ),
    ]
