# Generated by Django 5.1.15 on 2026-02-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_product_is_free_shipping_shippingplan_shippingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingplan',
            name='shipping_type',
        ),
        migrations.RemoveField(
            model_name='shippingrule',
            name='state',
        ),
    ]
