# Generated by Django 5.1.15 on 2026-01-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_remove_addressmaster_store_remove_banner_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='store',
        ),
    ]
