# Generated by Django 5.1.15 on 2025-12-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_displayproducts_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
