# Generated by Django 5.1.15 on 2026-02-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_product_is_free_shipping_shippingplan_shippingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
