# Generated by Django 5.1.15 on 2026-01-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_remove_user_store_remove_userotp_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='store',
        ),
        migrations.RemoveField(
            model_name='tempuser',
            name='store',
        ),
    ]
