# Generated by Django 5.1.15 on 2025-12-18 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screen', models.CharField(choices=[('Home', 'Home')], max_length=20)),
                ('image', models.CharField(max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('action', models.BooleanField(default=False)),
                ('destination', models.JSONField()),
            ],
            options={
                'db_table': 'banner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='DisplayProducts',
            new_name='DisplayProduct',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AlterModelTable(
            name='displayproduct',
            table=' display_product',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
