# Generated by Django 5.1.15 on 2025-12-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_banner_rename_displayproducts_displayproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
