# Generated by Django 5.1.15 on 2026-01-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_remove_coupon_store_remove_tempuser_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmaster',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='displayproduct',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertimelines',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempuser',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userotp',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='store_id',
            field=models.UUIDField(default='fed92080-9be0-46e7-b4ea-b6d3e6d6bf1e'),
            preserve_default=False,
        ),
    ]
