# Generated by Django 5.1.15 on 2026-02-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_alter_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
