# Generated by Django 5.1.15 on 2026-02-24 05:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_order_shipping_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='sms_auth_key',
        ),
        migrations.RemoveField(
            model_name='store',
            name='sms_delivered_template_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='sms_order_template_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='sms_otp_template_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='sms_packed_template_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='sms_sender_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='sms_shipped_template_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='store',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='store',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='store',
            name='smtp_use_tls',
        ),
        migrations.RemoveField(
            model_name='store',
            name='smtp_username',
        ),
        migrations.RemoveField(
            model_name='store',
            name='url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='webhook',
        ),
        migrations.AlterField(
            model_name='store',
            name='highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
