# Generated by Django 5.1.15 on 2026-01-08 12:56

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_addressmaster_store_id_banner_store_id_cart_store_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleBanner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.UUIDField()),
                ('screen', models.CharField(choices=[('Home', 'Home'), ('Wishlist', 'Wishlist')], max_length=20)),
                ('image', models.CharField(max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('action', models.BooleanField(default=False)),
                ('destination', models.JSONField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('product_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('discount', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'flash_sale_banner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebBanner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.UUIDField()),
                ('screen', models.CharField(choices=[('Home', 'Home'), ('Wishlist', 'Wishlist')], max_length=20)),
                ('image', models.CharField(max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('action', models.BooleanField(default=False)),
                ('destination', models.JSONField()),
            ],
            options={
                'db_table': 'web_banner',
                'ordering': ['-created_at'],
            },
        ),
    ]
