# Generated by Django 5.1.15 on 2025-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_remove_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='qer123', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
