# Generated by Django 5.1.15 on 2025-12-18 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('sku', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Purchase_return', 'Purchasereturn'), ('Sale_return', 'Salereturn')], max_length=20)),
                ('date', models.DateTimeField()),
                ('user', models.UUIDField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_before', models.PositiveIntegerField(default=0)),
                ('quantity_after', models.PositiveIntegerField(default=0)),
                ('purchase_rate_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_rate_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_input', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_output', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['-created_at'],
            },
        ),
    ]
