# Generated by Django 5.1.15 on 2026-01-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_flashsalebanner_webbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsalebanner',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='flashsalebanner',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flashsalebanner',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
