# Generated by Django 5.1.15 on 2026-01-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_flashsalebanner_description_flashsalebanner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=10),
            preserve_default=False,
        ),
    ]
