# Generated by Django 5.1.15 on 2025-12-19 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address_name', models.CharField(max_length=50)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], max_length=20)),
                ('full_address', models.JSONField()),
                ('house_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=25)),
                ('area_name', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('landmark', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'address',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Sell', 'Sell'), ('Purchase_return', 'Purchasereturn'), ('Sale_return', 'Salereturn')], max_length=20),
        ),
    ]
