# Generated by Django 5.1.15 on 2025-12-19 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]


    operations = [
        migrations.CreateModel(
            name='PinCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=25)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pincode',
            },
        ),
        migrations.RenameField(
            model_name='addressmaster',
            old_name='area_name',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='addressmaster',
            old_name='state_name',
            new_name='state',
        ),
    ]
