# Generated by Django 5.1.15 on 2026-01-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
