# Generated by Django 5.1.15 on 2026-02-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_store_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='is_active',
        ),
    ]
