# Generated by Django 5.1.15 on 2026-02-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_remove_visitor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='fcm_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
