# Generated by Django 5.1.15 on 2025-12-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_pincode_rename_area_name_addressmaster_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmaster',
            name='full_address',
        ),
    ]
