# Generated by Django 5.1.15 on 2026-01-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_alter_orderproducts_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
    ]
