# Generated by Django 5.1.15 on 2025-12-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_remove_addressmaster_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmaster',
            name='full_address',
            field=models.CharField(default='qwertyu', max_length=100),
            preserve_default=False,
        ),
    ]
