# Generated by Django 5.1.15 on 2026-02-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_discount_discountproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-29 08:45:27.057957+00', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discountproduct',
            name='created_by',
            field=models.CharField(max_length=255, null=True, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='discountproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AddField(
            model_name='discountproduct',
            name='updated_by',
            field=models.CharField(max_length=255, null=True, verbose_name='Updated By'),
        ),
    ]
