# Generated by Django 5.1.15 on 2025-12-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_addressmaster_full_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmaster',
            name='landmark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
