# Generated by Django 5.1.15 on 2026-03-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_inventorybatch_inventorytransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colour_code',
            field=models.CharField(default='000000', max_length=50),
        ),
    ]
