# Generated by Django 5.1.15 on 2025-12-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_alter_addressmaster_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
