# Generated by Django 5.1.15 on 2026-01-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingdetails',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
    ]
