# Generated by Django 5.1.15 on 2026-01-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_alter_ordershippingdetails_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingdetails',
            name='courier_service',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordertimelines',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(max_length=50),
        ),
    ]
