# Generated by Django 5.1.15 on 2026-01-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_alter_ordershippingdetails_courier_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.CharField(max_length=200),
        ),
    ]
