# Generated by Django 5.1.15 on 2026-03-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_subscriptionplan_webhooklog_storesubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_PACKED', 'Order Packed'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('OTP_AUTHENTICATION', 'Otp Authentication'), ('ADMIN_ORDER_RECEIVED', 'Admin Order Received')], max_length=50),
        ),
    ]
