# Generated by Django 5.1.15 on 2025-12-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_cashfree_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Placed', 'Placed'), ('Failed', 'Failed'), ('Confirmed', 'Confirmed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Outfordelivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Returnrequested', 'Return Requested'), ('Returned', 'Returned'), ('Refunded', 'Refunded'), ('Unfulfilled', 'Unfulfilled'), ('Cancelled', 'Cancelled')]),
        ),
    ]
