# Generated by Django 5.1.15 on 2026-03-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_iftarbookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iftarbookings',
            name='cf_session_id',
            field=models.CharField(max_length=1000),
        ),
    ]
