# Generated by Django 5.1.15 on 2026-01-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_alter_payment_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='sku',
            field=models.CharField(max_length=20),
        ),
    ]
