# Generated by Django 5.1.15 on 2026-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_alter_iftarbookings_cf_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='client_id',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='client_secret',
            field=models.CharField(null=True),
        ),
    ]
