# Generated by Django 5.1.15 on 2026-03-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_alter_store_client_id_alter_store_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
