# Generated by Django 5.1.15 on 2026-01-13 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_alter_payment_order_id_alter_payment_txn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayproduct',
            name='total_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.UUIDField()),
                ('product_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('rating', models.PositiveIntegerField()),
                ('review', models.CharField(default='', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'productreviews',
                'indexes': [models.Index(fields=['user_id'], name='productrevi_user_id_364ef1_idx'), models.Index(fields=['product_id'], name='productrevi_product_818b75_idx')],
            },
        ),
    ]
