# Generated by Django 5.1.15 on 2026-03-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_payment_remarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IftarBookings',
        ),
    ]
