# Generated by Django 5.1.15 on 2026-01-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0036_displayproduct_total_rating_productreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayproduct',
            name='rating',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
