# Generated by Django 5.1.15 on 2026-01-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_alter_displayproduct_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='username',
            field=models.CharField(default='System', max_length=30),
        ),
    ]
