# Generated by Django 5.1.15 on 2026-03-31 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_user_created_at_user_created_by_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershippingdetails',
            name='order_id',
        ),
        migrations.AddField(
            model_name='ordershippingdetails',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to='db.order'),
        ),
    ]
