# Generated by Django 5.1.15 on 2026-04-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_remove_ordershippingdetails_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='bo_subtitle',
        ),
        migrations.RemoveField(
            model_name='store',
            name='bo_title',
        ),
        migrations.RemoveField(
            model_name='store',
            name='highlights',
        ),
    ]
