# Generated by Django 5.1.15 on 2026-01-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
