# Generated by Django 5.1.15 on 2026-04-10 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_remove_store_bo_subtitle_remove_store_bo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOnboarding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_email', models.EmailField(max_length=255)),
                ('business_phone', models.CharField(max_length=15)),
                ('mobile_number', models.CharField(max_length=15)),
                ('payment_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='INITIATED', max_length=20)),
                ('payment_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business_onboarding',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='cloudfront_domain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_transaction_id', models.CharField(max_length=255, unique=True)),
                ('phonepe_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='INITIATED', max_length=20)),
                ('payment_url', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='db.businessonboarding')),
            ],
            options={
                'db_table': 'payment_transaction',
            },
        ),
    ]
