# Generated by Django 5.1.15 on 2026-04-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_businessonboarding_store_cloudfront_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
