# Generated by Django 5.1.15 on 2026-01-16 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_alter_contactmessage_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displayproduct',
            old_name='default_product_id',
            new_name='old_default_product_id',
        ),
        migrations.RenameField(
            model_name='displayproduct',
            old_name='variant_product_id',
            new_name='old_variant_product_id',
        ),
        migrations.AddField(
            model_name='displayproduct',
            name='default_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_products', to='db.product'),
        ),
        migrations.AddField(
            model_name='displayproduct',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='variant_of', to='db.product'),
        ),
    ]
