# Generated by Django 5.1.15 on 2026-04-28 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay'), ('phonepe', 'PhonePe'), ('cashfree', 'CashFree')], max_length=20)),
                ('client_id', models.CharField(max_length=255, null=True)),
                ('client_secret', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway', to='db.store')),
            ],
            options={
                'db_table': 'store_payment_gateway',
                'indexes': [models.Index(fields=['store'], name='store_payme_store_i_3d0839_idx'), models.Index(fields=['is_active', 'store'], name='store_payme_is_acti_b2a86f_idx'), models.Index(fields=['is_active'], name='store_payme_is_acti_6b49b1_idx')],
            },
        ),
    ]
