# Generated by Django 5.1.15 on 2026-01-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_rename_default_product_id_displayproduct_old_default_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displayproduct',
            old_name='old_variant_product_id',
            new_name='variant_product_id',
        ),
        migrations.RemoveField(
            model_name='displayproduct',
            name='variants',
        ),
    ]
