# Generated by Django 5.1.15 on 2026-01-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_rename_old_variant_product_id_displayproduct_variant_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='product_id',
            new_name='old_product_id',
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='db.product'),
        ),
    ]
