# Generated by Django 5.1.15 on 2026-04-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_storepaymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ph_order_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ph_redirect_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cf_order_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
