# Generated by Django 5.1.15 on 2026-01-16 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_rename_product_id_orderproducts_old_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_user_id_9b8b23_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_product_8a6792_idx',
        ),
        migrations.RemoveIndex(
            model_name='wishlist',
            name='wishlist_user_id_2af636_idx',
        ),
        migrations.RemoveIndex(
            model_name='wishlist',
            name='wishlist_product_ab5d67_idx',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='old_product_id',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_id',
            new_name='old_product_id',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='db.product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='db.product'),
        ),
    ]
