# Generated by Django 5.1.15 on 2026-04-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_payment_ph_order_id_payment_ph_redirect_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='gateway',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
