# Generated by Django 5.1.15 on 2026-05-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0044_webhooklog_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ph_redirect_url',
            field=models.TextField(null=True),
        ),
    ]
