# Generated by Django 5.1.15 on 2026-01-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0044_remove_cart_cart_user_id_9b8b23_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='old_product_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='old_product_id',
        ),
    ]
