# Generated by Django 5.1.15 on 2026-08-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_alter_payment_ph_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
