# Generated by Django 5.1.15 on 2026-01-16 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_remove_cart_old_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productreviews',
            name='productrevi_product_818b75_idx',
        ),
        migrations.RemoveField(
            model_name='productreviews',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productreviews',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='db.product'),
        ),
    ]
