# Generated by Django 5.1.15 on 2026-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_remove_productreviews_productrevi_product_818b75_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayproduct',
            name='old_default_product_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
