# Generated by Django 5.1.15 on 2026-01-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_alter_displayproduct_old_default_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='old_product_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
