# Generated by Django 5.1.15 on 2026-01-17 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0048_alter_orderproducts_old_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='db.displayproduct'),
        ),
    ]
