# Generated by Django 5.1.15 on 2026-01-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0049_alter_orderproducts_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='old_product_id',
        ),
    ]
